version: "3.7"

services:
  www:
    depends_on:
      - db
    restart: always
    deploy:
      restart_policy:
        condition: any
    image: apache-php:alpine
    build: ../images/apache-php/image
    volumes:
      - ${SITE_PATH}:/var/www/localhost/htdocs
      - ${LOG_PATH:?}:/var/log/apache2
    ports:
      - "${SITE_PORT:-80}:80"
    networks:
      - wamp-net

  db:
    restart: always
    deploy:
      restart_policy:
        condition: any
    image: mariadb:alpine
    build: ../images/mariadb-alpine/image
    volumes:
      - ${SQL_PATH:-mariadb-volume}:/var/lib/mysql
    environment:
      - DB_ROOT_PASS=${SQL_ROOT_PASSWORD}
      - DB_USER=${SQL_USER}
      - DB_PASS=${SQL_PASS}
    networks:
      - wamp-net

  adminer:
    restart: always
    deploy:
      restart_policy:
        condition: any
    depends_on:
            - db
    image: adminer:standalone
    ports:
      - "${ADMINER_PORT:-81}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=${ADMINER_THEME:-nette}
    networks:
      - wamp-net

networks:
  wamp-net:

volumes:
  mariadb-volume:
